name: Build & Release Factory Images [Release]

on:
  release:
    types: [released]

permissions:
  checks: write
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Factory ${{ matrix.build_type }}"
    strategy:
      fail-fast: false
      matrix:
        build_type: ["lv07"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'
      - name: Build web dist
        working-directory: ./main/http_server/axe-os
        run: |
          npm ci
          npm run build
      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5.2
          target: esp32s3
          command: GITHUB_ACTIONS="true" idf.py build
          path: '.'
      - name: "esp-idf build factory config for ${{ matrix.build_type }}"
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5.2
          target: esp32s3
          command: /opt/esp/idf/components/nvs_flash/nvs_partition_generator/nvs_partition_gen.py generate config-${{ matrix.build_type }}.cvs config.bin 0x6000
          path: '.'
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install esptool
      - name: "Create factory image for ${{ matrix.build_type }}-${{ github.ref_name }}"
        run: "./merge_bin.sh -c esp-miner-factory-${{ matrix.build_type }}-${{ github.ref_name }}.bin"
      - name: Release esp-miner.bin
        uses: softprops/action-gh-release@v2.4.2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "esp-miner-factory-${{ matrix.build_type }}-${{ github.ref_name }}.bin"
#      - name: Install rclone
#        run: |
#          curl -fsSL https://rclone.org/install.sh | sudo bash
#      - name: Upload to Cloudflare R2 using rclone
#        if: startsWith(github.ref, 'refs/tags/')
#        env:
#          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
#        run: |
#          mkdir -p ~/.config/rclone
#          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf
#          rclone copyto "esp-miner-factory-${{ matrix.build_type }}-${{ github.ref_name }}.bin" \
#            "r2:esp-miner/${{ github.ref_name }}/esp-miner-factory-${{ matrix.build_type }}-${{ github.ref_name }}.bin" \
#            --s3-acl public-read --s3-no-check-bucket
